kind: pipeline
type: docker
name: bookmarkPublish

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: devHost
      port: 22
      user: root
      key:
        from_secret: privateSsh
      command_timeout: 30m
      script:
        - cd /root/bookmark && git pull && bash build.sh && bash syncFile.sh